@startuml

skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #444
allow_mixing

class BaseScreen #WhiteSmoke {
    + apply_custom_styles()
    + render_navbar()
    + render_banner()
    + get_base64_image()
    + render_footer()
    + navigate_to()
}

package TemplateMethod2 {

    Interface ScreenTemplate #WhiteSmoke {
        + type
        + show_window()
    }


    class HomeScreen #WhiteSmoke {
        + show_window()
    }

    class ItineraryListScreen #WhiteSmoke {
        + show_window()
    }

    class LoginScreen #WhiteSmoke {
        + auth_manager
        + cookie_manager

        + show_window()
    }

    class RegisterScreen #WhiteSmoke{
        + user_manager

        + show_window()
    }

    class ResponseScreen #WhiteSmoke {
        + user_id
        + itinerary_manager: ItineraryManager
        + attraction_manager: AttractionManager

        + generate_pdf()
        + render_pdf_button()
        + show_window()
    }

    class RequestScreen #WhiteSmoke {
        + tourism_preference: TourismPreference
        + show_window()
    }

}
class TourismPreference #SkyBlue {
    + neigh
    + init_date
    + end_date
    + attr_preferences
    + lunch_preferences
    + budget

}

class FeedbackTripGuide #SkyBlue {
    + trip_guide: TripGuideDay
    + generate_data()
}

class TripGuideDay #SkyBlue {
    + name
    + days[Day]
    --
    + add_day()
    + generate_data()
}

class Day #SkyBlue {
    + date
    + day_of_week
    + breakfast
    + morning
    + lunch
    + afternoon
    + dinner
    + evening

    + add_morning_activity()
    + add_afternoon_activity()
    + add_evening_activity()
}

class TripGuideDayBuilder #SkyBlue {
    + tourism_preference: TourismPreference
    + chat_gpt_ai: ChatGptAI

    + build_question_message_llm()
    + ask_chat_gpt_about_attractions()
    + build_trip_guide_day()
}

package TemplateMethod {
    abstract ChatGptAI #LightYellow {
        + embeddings
        + llm
        + documents

        + load_documents_from_sqlite_url()
        + load_documents_from_csv()
        + build_chain()
        + retrieve_info()
        + generate_response()
        ~{abstract} set_template()
        ~{abstract} set_prompt()
    }

    class RioAttractionML #SkyBlue{
        + set_template()
        + set_prompt()
    }
}

class TripPlanner #WhiteSmoke {
    + tourism_preference: TourismPreference
    + user_id
    + attraction_manager
    + itinerary_manager

    + process_preferences()
    + map_budget_to_number()
    + process_trip()
    - _get_or_create_attraction()
}

class AttractionManager #WhiteSmoke {
    + session

    + get_attraction_by_name()
    + insert_attraction()
}

class AuthManager #WhiteSmoke {
    + hash_password()
    + authenticate_user()
    + logout()
}

class ItineraryManager #WhiteSmoke {
    + create_itinerary()
    + get_itinerary_data()
    + add_to_includes()
    + get_user_itineraries()
    + delete_itinerary()
}

class PageManager #WhiteSmoke {
    + set_page()
    + get_page()
    + get_page_args()
    + render_current_page()
    + _render_page()
}

class UserManager #WhiteSmoke {
    + is_email_registered()
    + add_user()
}

package Singleton {

    class SessionManager #WhiteSmoke {
        + _instance
    }
}

BaseScreen --- ScreenTemplate
ScreenTemplate  <|-- LoginScreen
ScreenTemplate <|-- ResponseScreen
ScreenTemplate <|-- RequestScreen
ScreenTemplate <|-- ItineraryListScreen
ScreenTemplate <|-- HomeScreen
ScreenTemplate <|-- RegisterScreen

ItineraryListScreen  "1" o-- "1" ItineraryManager

ResponseScreen "1" o-- "1" ItineraryManager
ResponseScreen "1" o-- "1" AttractionManager

PageManager "1" o-- "1" BaseScreen
LoginScreen "1" o-- "1" AuthManager
RegisterScreen "1" o-- "1" UserManager

ChatGptAI <|-- RioAttractionML

TripGuideDay "1" *-- "+" Day

FeedbackTripGuide "1" *-- "1" TripGuideDay

TripGuideDayBuilder "1" o-- "1" TourismPreference 
TripGuideDayBuilder "1" o--- "1" TripGuideDay  
TripGuideDayBuilder "1" o--- "1" ChatGptAI

TripPlanner "1" o-- "1" TripGuideDayBuilder
TripPlanner "1" o-- "1" TourismPreference
TripPlanner "1" o-- "1" ItineraryManager
TripPlanner "1" o-- "1" AttractionManager

RequestScreen "1" o-- "1" TourismPreference
ResponseScreen  "1" o-- "1" TripGuideDay

AttractionManager "1" --- "1" SessionManager
AuthManager "1" --- "1" SessionManager
ItineraryManager "1" --- "1" SessionManager
UserManager "1" --- "1" SessionManager
TripPlanner "1" --- "1" SessionManager

legend right 
    | Color | Type |
    |<#WhiteSmoke>| Instance |
    |<#SkyBlue>| Frozen Spot |
    |<#LightYellow>| Hot Spot|
endlegend

@enduml