"""Initial migration

Revision ID: e052587c6a4b
Revises: 
Create Date: 2024-11-18 17:22:41.986203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e052587c6a4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atracao',
    sa.Column('id_atracao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('horario_funcionamento', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_atracao')
    )
    op.create_table('roteiro',
    sa.Column('id_roteiro', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('orcamento', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_roteiro')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedback',
    sa.Column('id_feedback', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_roteiro', sa.Integer(), nullable=False),
    sa.Column('id_atracao', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_atracao'], ['atracao.id_atracao'], ),
    sa.ForeignKeyConstraint(['id_roteiro'], ['roteiro.id_roteiro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_feedback')
    )
    op.create_table('possui',
    sa.Column('id_possui', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_roteiro', sa.Integer(), nullable=False),
    sa.Column('preferencia', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_roteiro'], ['roteiro.id_roteiro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_possui')
    )
    op.create_table('restaurante',
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('id_atracao', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=120), nullable=False),
    sa.Column('vegetariano', sa.Boolean(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_atracao'], ['atracao.id_atracao'], ),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('tem',
    sa.Column('id_tem', sa.Integer(), nullable=False),
    sa.Column('id_roteiro', sa.Integer(), nullable=False),
    sa.Column('id_atracao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_atracao'], ['atracao.id_atracao'], ),
    sa.ForeignKeyConstraint(['id_roteiro'], ['roteiro.id_roteiro'], ),
    sa.PrimaryKeyConstraint('id_tem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tem')
    op.drop_table('restaurante')
    op.drop_table('possui')
    op.drop_table('feedback')
    op.drop_table('usuario')
    op.drop_table('roteiro')
    op.drop_table('atracao')
    # ### end Alembic commands ###
