[tool.poetry]
name = "where-to-rio"
version = "0.1.0"
description = ""
authors = ["Igor Soares, Luiz Felipe, Iury Rosal"]
readme = "README.md"
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.39.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
