"""Create tables

Revision ID: 75aa8d6f9bc0
Revises: 
Create Date: 2024-11-19 22:26:36.096775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75aa8d6f9bc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction',
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('operating_hours', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('attraction_id')
    )
    op.create_table('itinerary',
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('itinerary_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.attraction_id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.itinerary_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('includes',
    sa.Column('includes_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.attraction_id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.itinerary_id'], ),
    sa.PrimaryKeyConstraint('includes_id')
    )
    op.create_table('owns',
    sa.Column('owns_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.itinerary_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('owns_id')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('vegetarian', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.attraction_id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    op.drop_table('owns')
    op.drop_table('includes')
    op.drop_table('feedback')
    op.drop_table('user')
    op.drop_table('itinerary')
    op.drop_table('attraction')
    # ### end Alembic commands ###
